
name: Run JAR File

on:
  push:
    branches: [ "main" ]
    
jobs:
 run-jar:
   runs-on: ubuntu-latest

   steps:
   - name: checkout code
     uses: actions/checkout@v3

   - name: Run JAR File
     run: java -jar *.jar
