
name: Run JAR File

on:
  push:
    branches: [ "main" ]
    
jobs:
 run-jar:
   runs-on: windows-latest

   steps:
   - name: checkout code
     uses: actions/checkout@v3
     
   - name: Set up JDK 17
     uses: actions/setup-java@v4
     with:
      java-version: '17'
      distribution: 'temurin'

   - name: Install Google Chrome
     run: |
        $chrome_installer = "C:\chrome_installer.exe"
        Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile $chrome_installer
        Start-Process -FilePath $chrome_installer -ArgumentList "/silent /install" -Wait
        Remove-Item -Force $chrome_installer

   - name: Install ChromeDriver
     run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+' | head -n1)
        echo "Chrome version: $CHROME_VERSION"
        sudo curl -sS -o /usr/local/bin/chromedriver "https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip"
        sudo chmod +x /usr/local/bin/chromedriver    

   - name: Run JAR File
     run: java -jar AegisHrms-0.0.1-SNAPSHOT-loginLogout.jar
