
name: Run JAR File

on:
  push:
    branches: [ "main" ]
    
jobs:
 run-jar:
   runs-on: windows-latest

   permissions:
      contents: read
      issues: write
      pull-requests: write

   steps:
   - name: checkout code
     uses: actions/checkout@v3
     
   - name: Set up JDK 17
     uses: actions/setup-java@v4
     with:
      java-version: '17'
      distribution: 'temurin'

   - name: Install Google Chrome
     run: |
        $chrome_installer = "C:\chrome_installer.exe"
        Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile $chrome_installer
        Start-Process -FilePath $chrome_installer -ArgumentList "/silent /install" -Wait
        Remove-Item -Force $chrome_installer
        
   - name: Run JAR File
     run: java -jar AegisHrms-0.0.1-SNAPSHOT-loginLogout.jar

   - name: Run JAR File
     run: java -jar AegisHrms-0.0.1-SNAPSHOT-addDepartment.jar

   - name: Generate JAR report
     run: |
        # Define the report file
        REPORT_FILE="jar_files_report.txt"

        # Clear or create the report file
        > $REPORT_FILE

        echo "JAR files in the repository:" >> $REPORT_FILE
        find . -type f -name '*.jar' >> $REPORT_FILE
        
        cat $REPORT_FILE

   - name: Upload report
     uses: actions/upload-artifact@v3
     with:
        name: jar-report
        path: jar_files_report.txt  
  
