
name: Run JAR File

on:
  push:
    branches: [ "main" ]
    
jobs:
 run-jar:
   runs-on: windows-latest

   permissions:
      contents: read
      issues: write
      pull-requests: write

   steps:
   - name: checkout code
     uses: actions/checkout@v3
     with:
        fetch-depth: 1
     
   - name: Set up JDK 17
     uses: actions/setup-java@v4
     with:
      java-version: '17'
      distribution: 'temurin'

   - name: Install Google Chrome
     run: |
        $chrome_installer = "C:\chrome_installer.exe"
        Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/standalonesetup64.exe" -OutFile $chrome_installer
        Start-Process -FilePath $chrome_installer -ArgumentList "/silent /install" -Wait
        Remove-Item -Force $chrome_installer

   - name: Run JAR files and generate report
     id: run-jars
     shell: pwsh
     run: |
          # Create a directory for reports
          New-Item -Path "reports" -ItemType Directory -Force

          # Example JAR files to run (adjust as needed)
          $jar_files = Get-ChildItem -Recurse -Filter *.jar

          # Create the report file
          $report_file = "reports/execution-report.md"
          "@| JAR File         | Status ||------------------|--------|" | Out-File -FilePath $report_file -Encoding utf8

          # Iterate over JAR files
          foreach ($jar in $jar_files) {
            Write-Output "Running $jar..."
            if (& java -jar $jar) {
              "@| $jar | Passed |" | Out-File -FilePath $report_file -Append -Encoding utf8
            } else {
              "@| $jar | Failed |" | Out-File -FilePath $report_file -Append -Encoding utf8
            }
          }

          # Output the report
          Get-Content -Path $report_file

   - name: Upload execution report as artifact
     uses: actions/upload-artifact@v3
     with:
          name: jar-execution-report
          path: reports/execution-report.md
